pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = 'laravel1-app'
        DOCKER_COMPOSE_VERSION = '1.29.2'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build DOCKER_IMAGE
                }
            }
        }

        stage('Run Tests') {
            steps {
                // You can add your test commands here
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh "docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build"
                }
            }
        }
    }

    post {
        always {
            script {
                sh "docker-compose -f docker-compose.yml -f docker-compose.prod.yml ps"
            }
        }
    }
}
