pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = 'laravel1-app'
        DOCKER_COMPOSE_VERSION = '1.29.2'
    }

    stage('Checkout') {
            steps {pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = 'laravel1-app'
        DOCKER_COMPOSE_VERSION = '1.29.2'
    }

    stages {
        stage('Checkout') {
            steps {
                // Specify the Git repository URL and branch
                checkout([$class: 'GitSCM', branches: [[name: 'main']], userRemoteConfigs: [[url: 'https://github.com/AvishkaKoswatta/DevOps2_Project1.git']]])

                // Specify the path to the docker-compose.yml file
                // Replace 'devops2/docker-compose.yml' with the correct path in your repository
                script {
                    def pathToDockerCompose = 'devops2/docker-compose.yml'
                    checkout([$class: 'GitSCM', branches: [[name: 'main']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'PathRestriction', excludedRegions: '', includedRegions: '', path: pathToDockerCompose]], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/AvishkaKoswatta/DevOps2_Project1.git']]])
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build DOCKER_IMAGE
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh "docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build"
                }
            }
        }
    }

    post {
        always {
            script {
                sh "docker-compose -f docker-compose.yml -f docker-compose.prod.yml ps"
            }
        }
    }
}

                // Specify the Git repository URL and branch
                checkout([$class: 'GitSCM', branches: [[name: 'main']], userRemoteConfigs: [[url: 'https://github.com/AvishkaKoswatta/DevOps2_Project1.git']]])

                // Specify the path to the docker-compose.yml file
                // Replace 'devops2/docker-compose.yml' with the correct path in your repository
                script {
                    def pathToDockerCompose = 'devops2/docker-compose.yml'
                    checkout([$class: 'GitSCM', branches: [[name: 'main']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'PathRestriction', excludedRegions: '', includedRegions: '', path: pathToDockerCompose]], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/AvishkaKoswatta/DevOps2_Project1.git']]])
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build DOCKER_IMAGE
                }
            }
        }

        
        stage('Deploy') {
            steps {
                script {
                    sh "docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build"
                }
            }
        }
    }

    post {
        always {
            script {
                sh "docker-compose -f docker-compose.yml -f docker-compose.prod.yml ps"
            }
        }
    }
}
