pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = 'laravel1-app:latest' // Tagging the Docker image
        DOCKER_COMPOSE_VERSION = '2.27.1'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from Git repository
                git branch: 'main', url: 'https://github.com/AvishkaKoswatta/DevOps2_project1.git'
            }
        }

        stage('Build and Deploy') {
            steps {
                // Build and deploy using Docker Compose
                script {
                    try {
                        sh """
                            docker-compose --version || curl -L "https://github.com/docker/compose/releases/download/\${DOCKER_COMPOSE_VERSION}/docker-compose-\$(uname -s)-\$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
                            docker-compose up -d
                        """
                    } catch (Exception e) {
                        echo "Failed to build and deploy: ${e.message}"
                        currentBuild.result = 'FAILURE'
                    }
                }
            }
        }
    }

    post {
        always {
            // Cleanup Docker resources
            script {
                sh "docker-compose down"
            }
        }
    }
}
